#:schema node_modules/wrangler/config-schema.json
name = "randomwk"
main = "src/index.tsx"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

workers_dev = false

[observability]
enabled = true

[[kv_namespaces]]
binding = "random"
id = "72c838629f3946b79de52953226f9cef"
